name: Main

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  build:
    name: Build
    needs: verify
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml

  security:
    name: Security
    uses: ./.github/workflows/security.yml
