name: Release

on:
  workflow_dispatch:

  push:
    tags: ["v*"]

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml

  verify:
    name: Verify
    needs: prepare
    uses: ./.github/workflows/verify.yml

  test:
    name: Test
    needs: verify
    uses: ./.github/workflows/test.yml

  package:
    name: Package
    needs: [prepare, test]
    uses: ./.github/workflows/package.yml

    with:
      version: ${{ needs.prepare.outputs.version }}

  checksum:
    name: Checksum
    needs: [prepare, package]
    uses: ./.github/workflows/checksum.yml

    with:
      version: ${{ needs.prepare.outputs.version }}

  publish:
    name: Publish
    needs: [prepare, checksum]
    uses: ./.github/workflows/publish.yml

    permissions:
      contents: write

    with:
      tag: ${{ needs.prepare.outputs.tag }}
      version: ${{ needs.prepare.outputs.version }}
      prerelease: ${{ needs.prepare.outputs.prerelease }}
