name: Test

on:
  workflow_call:

jobs:
  cli:
    name: CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        name: Checkout Code

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust Toolchain

        with:
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2
        name: Cache Cargo

      - run: cargo install cargo-llvm-cov
        name: Install cargo-llvm-cov

      - run: cargo llvm-cov --fail-under-lines 80 --workspace --html
        name: Run Tests

      - uses: actions/upload-artifact@v4
        name: Upload Coverage Report
        with:
          name: coverage-report
          path: target/llvm-cov/
